name: Deploy to Hostinger Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 65002 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy ke Hostinger
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 65002 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          set -e
          cd /home/${{ secrets.SSH_USERNAME }}/public_html
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan cache:clear
          php artisan config:clear
          php artisan storage:link
          EOF
